### ISSUE TITLE
unable to copy settings file / settings file missing

### ISSUE THREAD

**Issue by jimmynash** [docksal/example-backdrop#1]
I was trying to spin up an example backdrop site using docksal and while most of it seems to complete something goes wrong with creating the settings file.

Ubuntu 16.04
fin 1.60.2

In my home directory ran the following:

1. fin project create
2. named project "droptest"
3. choose 9 for backdrop
4. fin does it's thing
5. Stops with message: "chmod: cannot access ‘/var/www/docroot/files/’: No such file or directory"
6. Site is running but without a settings file. It can be accessed but gives a requirements problem of missing settings.php file

I looked at the init command and the env files but I'm not sure why it would choose "/var/www/docroot" and not the current project root where the create command was run from.

**Comment by sean-e-dietrich** [comment]
@jimmynash thanks for bringing this to our attention. It appears as though normally you don't commit the settings.php and this time around we actually didn't commit that nor the files directory either, even though it contained no actual files in it. We are currently pushing a fix in the following PR https://github.com/docksal/example-backdrop/pull/2 which should hopefully fix everything.

To answer you about the `fin project create` it does create the main project folder in whatever directory you are in. But the way docksal works is that it runs all commands within the docker containers. The path within the docker containers is `/var/www/docroot`. This is so that you aren't required to run any additional software or different versions of PHP on you machine in order to get a site running.

**Comment by jimmynash** [comment]
@sean-e-dietrich Excellent! Thanks for the explanation. Looking forward to the pull request landing.

Thanks!

**Comment by jimmynash** [comment]
I think this can be closed. The last time I spun up a backdrop site I had no problems.
